### ISSUE TITLE
C-w doesn't delete word in insert mode

### ISSUE THREAD

**Issue by rgrinberg** [hood/popui.nvim#10]
While inside the pop-up, I would expect `C-w` to delete a word backwards rather than act like `C-w` in normal mode.

**Comment by hood** [comment]
Well, that's an interactive prompt which isn't expected to work as an input mode buffer, but why not? `C-w` wouldn't overlap with anything else in the input popup, so adding that behaviour is a good UX suggestion IMHO.
I'll implement it as soon as I get time to, thank you.

**Comment by hood** [comment]
Done! Thank you for your valuable suggestion!
