### ISSUE TITLE
Error: 'replacement string' items contain newlines

### ISSUE THREAD

**Issue by lyokha** [hood/popui.nvim#15]
When the list of choices have a title with multiple lines I get this error and the items in the popui window turn not selectable.

Particularly, *haskell-language-server* pops up the following (yet stupid) choice when some dependencies are missing:

```
Failed to find the GHC version of this Cabal project.
Error when calling cabal exec -v0 -- ghc --print-libdir:
1: Try to restart
Type number and <Enter> or click with the mouse (q or empty cancels):
```

Note the two lines before the choice.

The following patch fixes the issue for me:

```diff
diff --git a/lua/popui/core.lua b/lua/popui/core.lua
index 246f766..c36b527 100644
--- a/lua/popui/core.lua
+++ b/lua/popui/core.lua
@@ -377,6 +377,8 @@ function Core:spawnListPopup(
 )
     local popupBufferNumber = self:createBuffer()
 
+    windowTitle = windowTitle:gsub("\n", " ")
+
     -- Create the popup, calculating its size based on the entries.
     local popupWindowId = self:createWindow(
         popupBufferNumber,
@@ -428,6 +430,8 @@ function Core:spawnInputPopup(
 )
     local popupBufferNumber = self:createBuffer()
 
+    windowTitle = windowTitle:gsub("\n", " ")
+
     -- Create the popup, calculating its size based on the entries.
     local popupWindowId = self:createWindow(
         popupBufferNumber,
```

There is another (seemingly unrelated) issue after applying the patch. The two string concatenates well but the tail gets lost, it prints only `Failed to find the GHC version of this Cabal project. Error when calling cabal exec -v0 -- ghc --print`, i.e. the `-libdir:` part was lost. This is something related to math: when I have replaced `+ 4` by `+6` in `getWindowConfiguration()`, the title was printed completely.

**Comment by lyokha** [comment]
Regarding the math issue: I'm not sure but it seems that `getWindowConfiguration()` should be `+ 6`:

```diff
diff --git a/lua/popui/core.lua b/lua/popui/core.lua
index 246f766..5d6c185 100644
--- a/lua/popui/core.lua
+++ b/lua/popui/core.lua
@@ -58,13 +58,13 @@ local function getWindowConfiguration(
 
     if popupType == Core.PopupTypes.List then
         popupWidth =
-            math.max(getLongestEntry(options.entries), #(windowTitle or "") + 4)
+            math.max(getLongestEntry(options.entries), #(windowTitle or "") + 6)
         popupHeight = options.height or #options.entries
     elseif popupType == Core.PopupTypes.Input then
         popupWidth = math.max(
             #(options.initialText or ""),
             #(windowTitle or "")
-        ) + 4
+        ) + 6
         popupHeight = 1
     end
```

because the width of the window is calculated from the width of the title before the two spaces get added to the title in `addTitleToWindow()`.

Btw here is how it looks:

1. `+ 4` (the original) 
![popui-no-tail](https://github.com/hood/popui.nvim/assets/1219667/3cca4c42-9611-4c8d-9046-a70587a87959)
2. `+ 6`
![popui](https://github.com/hood/popui.nvim/assets/1219667/67f20fdd-8e65-4502-81db-9a0c824f6b4b)

**Comment by lyokha** [comment]
Not  sure what `options.initialText` is, so the math patch may also look as

```diff
diff --git a/lua/popui/core.lua b/lua/popui/core.lua
index 246f766..1f7fb9c 100644
--- a/lua/popui/core.lua
+++ b/lua/popui/core.lua
@@ -58,12 +58,12 @@ local function getWindowConfiguration(
 
     if popupType == Core.PopupTypes.List then
         popupWidth =
-            math.max(getLongestEntry(options.entries), #(windowTitle or "") + 4)
+            math.max(getLongestEntry(options.entries), #(windowTitle or "") + 6)
         popupHeight = options.height or #options.entries
     elseif popupType == Core.PopupTypes.Input then
         popupWidth = math.max(
             #(options.initialText or ""),
-            #(windowTitle or "")
+            #(windowTitle or "") + 2
         ) + 4
         popupHeight = 1
     end
```

**Comment by hood** [comment]
Hey, thanks for using the library and providing a solution for this issue! It looks fine to me, do you want to contribute with a PR or shall I proceed and implement it myself?

**Comment by lyokha** [comment]
Hi @hood, I created a PR.
