### ISSUE TITLE
Behavior on <ESC> or <Ctrl-C>

### ISSUE THREAD

**Issue by wookayin** [hood/popui.nvim#2]
When the popup menu is open, both`<Ctrl-C>` and <ESC> should cancel and exit the menu immediately.

Currently, `<Ctrl-C>` does nothing, and `<Esc>` does not exit the menu immediately (only after timeout) when there are other mappings that is prefixed by `<Esc>`.

**Comment by hood** [comment]
Feature implemented.

**Comment by wookayin** [comment]
3f41f5bdfe426890d5a693af2d4c8b5ad7372f69 looks good. thanks!
