### ISSUE TITLE
Popup for Variable Renaming (vim.ui.input)

### ISSUE THREAD

**Issue by mike-lloyd03** [hood/popui.nvim#3]
Thanks for this. It works great when running code actions. Is there any way this can be expanded to include renaming variables? I believe this is the vim.ui.input API.

**Comment by mike-lloyd03** [comment]
I've started a PR for this.

https://github.com/hood/popui.nvim/pull/4

**Comment by hood** [comment]
Great, I've wanted to do this a for a while, but never found the time/willpower to start looking into it. Great idea btw!

**Comment by hood** [comment]
Closed in #4 .
