### ISSUE TITLE
Error when calling popui.diagnostics-navigator

### ISSUE THREAD

**Issue by trueegorletov** [hood/popui.nvim#5]
Command ` :lua require'popui.diagnostics-navigator'()` causes an error:
![Screenshot 2022-06-25 at 18 24 45](https://user-images.githubusercontent.com/105159089/175780220-f8bd25cd-6f1f-40da-b853-7069e0756b8e.png)

**Comment by hood** [comment]
Hello and thank you for using `popui.nvim`! 
I have just pushed a temporary fix I committed locally a few weeks ago. It shouldn't error now, but I gotta take some time to investigate why `row`  and/or `col` are `nil` sometimes...

**Comment by hood** [comment]
Fixed in https://github.com/hood/popui.nvim/commit/f64004bbe9d3c8ae5a472c8d9d7f001d029acf76
