### ISSUE TITLE
Unable to open diagnostics navigator again

### ISSUE THREAD

**Issue by trueegorletov** [hood/popui.nvim#6]
Hello! Thanks for your plugin.

I had some break so I guess it is not caused by any new commits. 
When I try to call require('pop.diagnostics-navigator')() I'm getting this error:

![Screenshot 2022-07-03 at 12 29 58](https://user-images.githubusercontent.com/105159089/177033816-e3eef530-e034-4907-9140-acd84b80f87d.png)

**Comment by hood** [comment]
Investigating as of right now... Will keep you updated.

**Comment by hood** [comment]
Just pushed a new commit in an attempt to fix this issue, assuming it was maybe caused by multiline strings being passed to the `message` field. Can you confirm it works now? Unfortunately I ain't got much time to test the fix and will attempt to brute force a solution for now.
