### ISSUE TITLE
CodeAction seems broken

### ISSUE THREAD

**Issue by Freyskeyd** [hood/popui.nvim#7]
Hello,

I use NvChad with Popui everything works fine except `code_action` and `diagnostics`.

![Screenshot 2022-11-03 at 11 58 23](https://user-images.githubusercontent.com/1394604/199710680-6bf01ba1-83c0-4cf7-b4bd-b2c99f3ecc1a.png)

How can I debug this ?

**Comment by Freyskeyd** [comment]
it seems that it's due to the absence of `vim.g.popui_border_style`

**Comment by hood** [comment]
Good morning, and thank you for using the plugin! I guess the broken part you're referring to is the missing popup borders, right? Have you tried setting them eplicitly?

You can define the borders style by setting
```
let g:popui_border_style = PREFERRED_STYLE
```
In your vimrc

**Comment by Freyskeyd** [comment]
Yes, it fixed the issue for `code_action` but not for diagnostics :x

**Comment by hood** [comment]
@Freyskeyd I have added a default fallback style for borders. Can you pull the latest version and check whether it fixes the issue for the diagnostics popup, too?

**Comment by Freyskeyd** [comment]
It didn't, but I'm using the default binding for diagnostics.

![Screenshot 2022-11-03 at 13 03 11](https://user-images.githubusercontent.com/1394604/199715872-940a329c-af10-45a3-8754-49d66bd364cc.png)

**Comment by hood** [comment]
Yes, I don't think you are `popui.nvim` at all for diagnostics.

You should spawn `popui.nvim`'s popup for navigating diagnostics by doing something the likes of:
```viml
nnoremap <YOUR_KEYMAP_HERE> :lua require'popui.diagnostics-navigator'()<CR>
```

**Comment by Freyskeyd** [comment]
I'm using binding to trigger: `vim.diagnostic.goto_prev`

Maybe we can add popui to that too

**Comment by hood** [comment]
`vim.diagnostic.goto_prev()` shouldn't display a popup at all IIRC, it's just a command that teleports the cursor to some coordinates. 
The popup you displayed in [this](https://github.com/hood/popui.nvim/issues/7#issuecomment-1302001768) comment is just the default popup for diagnostics you get on a given line.
What is the feature that you feel should be incoprporated in `popui.nvim`?

**Comment by Freyskeyd** [comment]
having the default popup override by popui.nvim ? I don't know if it's possible tho

**Comment by hood** [comment]
I don't see much value in doing that. The only real "benefit" we'de get would be a different style for the title. Custom borders in native NeoVim popups can already be configured by passing
```lua
{
	border = "rounded",
}
```
to the handler.
