### ISSUE TITLE
no response on popui.diagnostics-navigator

### ISSUE THREAD

**Issue by gilbh** [hood/popui.nvim#9]
Hi,

I am very curious about this plugin, but can't get it to work. Running NeoVide on Windows. When typing:
```
:lua require'popui.diagnostics-navigator'()
```
-- nothing happens. (Not even an error?). 

The plug is installed, I have the following lines inside the lua section of my vimrc:
```
  vim.ui.select = require"popui.ui-overrider"
  vim.ui.input = require"popui.input-overrider"
```

Thanks!

**Comment by hood** [comment]
Hi, and thank you for investing your time into trying the plugin and writing the issue!
Are you sure you have diagnostics being reported at all in the current buffer?
If you have doubts about how to debug diagnostics, try running `:LspInfo` while in the buffer, then paste the paste the results here so I can take a look at your LSP status and help you.

**Comment by gilbh** [comment]
Thanks for the quick reply!
I don't have an editor command `LspInfo` set up (I use a jedi lsp for Python), so I gather from your reply that the diagnostics only works with the native nvim lsp? 

Also, what about the two overrides `ui-overrider`, `input-overrider`? I would assume these are automatically hooked? I cannot spot any change in interaction with nvim ui ... maybe I do not understand the use/purpose of your plugin?

Thanks again for helping.

**Comment by hood** [comment]
Yup, all three commands depend on a language server being attached to the current buffer, and reporting diagnostics and the availability of code actions to the editor.
Not having `:LspInfo` available looks strange to me, but I'm not 100% sure it's a built-in command either. Would you mind sharing your dotfiles? I suspect your language server is not being attached at all.

ui-overrider and input-overrider should spawn a floating interactive popup instead of the built-in UIs provided by the editor. You should see the difference in situations like calling the LSP rename action. If you're not sure, you could also attach some screenshots of what you're seeing so I can tell you if that's the expected UI.

**Comment by gilbh** [comment]
Thanks. This is something interesting for me to learn more about. Great! 

I will look around regarding `:LspInfo`. In the meantime, I am attaching _vimrc (which means: Windows ...). I don't use separate lua files etc., and you will see the file is really a mess (over 1,200 lines ...). Sorry for that. (And I've changed
[_vimrc.txt](https://github.com/hood/popui.nvim/files/9984780/_vimrc.txt)
 extension to .txt since github says _vimrc file type is not supported).

**Comment by gilbh** [comment]
From what a friend just told me, `:LspInfo` is not a builtin. It comes from another plugin:
https://github.com/neovim/nvim-lspconfig

**Comment by hood** [comment]
Yes, that's why I wasn't 100% sure. I'm just off my computer and couldn't check when writing the comment. Try doing
```
:lua print(vim.inspect(vim.tbl_keys(vim.lsp.handlers)))
```

And paste the results here, it should print a lua table containing all available lsp actions handlers.

**Comment by gilbh** [comment]
Thanks. Here it is:
```

{ "workspace/executeCommand", "textDocument/definition", "textDocument/implementation", "textDocument/rangeFormatting", "textDocument/documentSymbol", "textDocument/formatting", "workspace/workspaceFolders", "textDocument/publishDiagnostics", "textDocument/documentHighlight", "callHierarchy/outgoingCalls", "window/logMessage", "textDocument/typeDefinition", "signature_help", "window/showMessage", "workspace/symbol", "hover", "textDocument/signatureHelp", "$/progress", "window/workDoneProgress/create", "window/showMessageRequest", "textDocument/declaration", "textDocument/hover", "textDocument/completion", "textDocument/rename", "client/registerCapability", "callHierarchy/incomingCalls", "workspace/configuration", "textDocument/codeLens", "textDocument/references", "workspace/applyEdit" }
```

**Comment by hood** [comment]
Could you try a `textDocument/rename` and screenshot the consequent prompt you're presented with?

**Comment by hood** [comment]
Any news on this?

**Comment by gilbh** [comment]
Thanks for checking in. I just tried it, but I don't really know lua and the following gives and error:
```
:lua textDocument/rename
```

What is the correct way of running this?

**Comment by hood** [comment]
Just try 
```
vim.api.nvim_set_keymap("n", "YOUR_KEYMAP_HERE", "<cmd>lua vim.lsp.buf.rename()<CR>", { noremap = true })
```
and then use it on something you'd want to rename.

**Comment by gilbh** [comment]
Thanks. I did this and nothing happens. I also tried:
```
:lua vim.lsp.buf.rename()
```
-- and nothing happens.

**Comment by hood** [comment]
Try doing it again WITHOUT having these two lines in your config:
```
  vim.ui.select = require"popui.ui-overrider"
  vim.ui.input = require"popui.input-overrider"
```

then report back. Sorry if this is taking so long, but unfortunately remote asynchronous debugging is always a pain.

**Comment by gilbh** [comment]
Not at all, I have patience ;-)

But still, even when I disable these two lines, and then run the line you asked, nothing happens.

**Comment by hood** [comment]
Well, I guess the problem is somewhere else then, not a `popui.nvim` issue at all.
